CREATE DATABASE SCHOOL;
USE SCHOOL;

CREATE TABLE SCHOOL(
	SNO INT PRIMARY KEY,
    SNAME VARCHAR(10),
    MARKS INT);

INSERT INTO SCHOOL VALUES(101, 'ANIK', 98);
INSERT INTO SCHOOL VALUES(102, 'DHIMAN', 54);
INSERT INTO SCHOOL VALUES(103, 'RAHUL', 43);

SELECT * FROM SCHOOL;

CREATE TABLE LIBRARY(
	SNO INT, FOREIGN KEY(SNO) REFERENCES SCHOOL(SNO),
    BOOK_NAME VARCHAR(10));

INSERT INTO LIBRARY VALUES(101, 'JAVA');
INSERT INTO LIBRARY VALUES(102, 'JAVASCRIPT');
INSERT INTO LIBRARY VALUES(103, 'C#');

SELECT * FROM LIBRARY;

INSERT INTO LIBRARY VALUES(104, 'PYTHON'); -- THIS WILL GIVES EN ERROR

DELETE FROM LIBRARY WHERE SNO=103 AND BOOK_NAME='PYTHON';

DELETE FROM LIBRARY WHERE SN0=101;


-- --------------------------------------------------------

CREATE TABLE LIBRARY1(
	SNO INT, FOREIGN KEY(SNO) REFERENCES SCHOOL(SNO) ON DELETE CASCADE,
    BOOK_NAME VARCHAR(10));
    
INSERT INTO LIBRARY1 VALUES(101, 'JAVA');
INSERT INTO LIBRARY1 VALUES(102, 'JAVASCRIPT');
INSERT INTO LIBRARY1 VALUES(103, 'C#');

SELECT * FROM LIBRARY1;

rollback;

DELETE FROM LIBRARY1 WHERE SNO=101;