USE mydb;

CREATE TABLE NSTUDENT(
	SID INT(4),
    SNAME VARCHAR(15));

DESCRIBE NSTUDENT;

INSERT INTO NSTUDENT VALUES(101, 'ANIK');
INSERT INTO NSTUDENT VALUES(102, 'RAHUL');
INSERT INTO NSTUDENT VALUES(103, 'DHIMAN');

SELECT * FROM NSTUDENT;

-- ADDING A NEW COLUMN IN THE TABLE
ALTER TABLE NSTUDENT ADD(GRADE VARCHAR(2));

DESCRIBE NSTUDENT;

-- DELETING A COLUMN FROM THE TABLE
ALTER TABLE NSTUDENT DROP COLUMN GRADE;

-- MODIFY THE EXISTING COLUMN SIZE
ALTER TABLE NSTUDENT MODIFY COLUMN SNAME VARCHAR(20);

-- RENAME A COLUMN
ALTER TABLE NSTUDENT RENAME COLUMN SNAME TO STUNAME;

-- RENAME A TABLE
RENAME TABLE NSTUDENT TO STUDENT1;
RENAME TABLE STUDENT1 TO NSTUDENT;
COMMIT;

-- UPDATE
SET SQL_SAFE_UPDATES = 0;

SELECT * FROM NSTUDENT;

-- UPDATE A SINGLE VALUE IN THE GIVEN ROW
UPDATE NSTUDENT SET GRADE='A+' WHERE SID=101;

-- UPDATE MULTIPLE VALUES IN THE GIVEN ROW
UPDATE NSTUDENT SET STUNAME='ANIK DAS' WHERE SID=101;
UPDATE NSTUDENT SET STUNAME='RAHUL DAS', GRADE='B+' WHERE SID=102;
UPDATE NSTUDENT SET STUNAME='DHIMAN ROY', GRADE='B' WHERE SID=103;

-- ADDING NEW COLUMN
ALTER TABLE NSTUDENT ADD(CITY VARCHAR(10));

-- UPDATE ALL ROWS
UPDATE NSTUDENT SET CITY='DHAKA';



