-- DML COMMANDS SCRIPT

-- FOR DISABLE THE AUTO COMMIT MODE
SET AUTOCOMMIT=0;

-- BEFORE DELETE AND UPDATE YOU NEED TO DISABLE SAFE UPDATE MODE
SET SQL_SAFE_UPDATES = 0;

-- SPECIFY THE DATABASE
USE MYDB;

-- RETRIVING THE DATA FROM TABLE
SELECT * FROM NSTUDENT;

-- DELETING ALL DATA FROM STUDENT
DELETE FROM NSTUDENT;

-- GEETING BACK THE DELETED DATA
ROLLBACK;

-- INSERTING DATA INTO THE TABLE
INSERT INTO NSTUDENT VALUES(101, 'ANIK');
INSERT INTO NSTUDENT VALUES(102, 'RAHUL');
INSERT INTO NSTUDENT VALUES(103, 'DHIMAN');
COMMIT;

-- PERMANENTLY ROLLBACK THE TABLE DATA, CAN NOT RETRIVE USING ROLLBACK COMMAND
TRUNCATE TABLE NSTUDENT;