-- SPECIFYING THE DATABASE
USE MYDB;

-- RETRIVING DATA FROM THE TABLE
SELECT * FROM EMPLOYEE;

ALTER  TABLE EMPLOYEE RENAME COLUMN SLARY TO SALARY;
ALTER TABLE EMPLOYEE RENAME COLUMN FRIST_NAME TO FIRST_NAME;

-- USE OF GROUP BY
SELECT DESIGNATION, SUM(SALARY) FROM EMPLOYEE GROUP BY DESIGNATION;
SELECT DESIGNATION, AVG(SALARY) FROM EMPLOYEE GROUP BY DESIGNATION;
SELECT DESIGNATION, MAX(SALARY), MIN(SALARY) FROM EMPLOYEE GROUP BY DESIGNATION;
SELECT DESIGNATION, COUNT(*) FROM EMPLOYEE GROUP BY DESIGNATION;
SELECT DESIGNATION, COUNT(*) FROM EMPLOYEE GROUP BY DESIGNATION HAVING COUNT(*) > 2;

-- USE OF ORDER BY
SELECT * FROM EMPLOYEE ORDER BY SALARY DESC;
SELECT * FROM EMPLOYEE ORDER BY FIRST_NAME;

