-- UNION OPERATION ON TABLES
USE MYDB;

CREATE TABLE A( 
	NUM INT(5), 
    GRADE VARCHAR (2));
    
    DESCRIBE A;
    
CREATE TABLE B(
	NUM INT(5),
	GRADE VARCHAR(2));
        
DESCRIBE B;

-- INSERTING DATA INTO TABLE A
INSERT INTO A VALUES(11, 'A');
INSERT INTO A VALUES(12, 'B');
INSERT INTO A VALUES(13, 'C');
INSERT INTO A VALUES(14, 'D');

-- RETRIVING DATA FROM TABLE A
SELECT * FROM A;

-- INSERTING DATA INTO TABLE B
INSERT INTO B VALUES(13, 'C');
INSERT INTO B VALUES(14, 'D');
INSERT INTO B VALUES(15, 'E');
INSERT INTO B VALUES(16, 'F');

-- RETRIVING DATA FROM TABLE B
SELECT * FROM B;

-- UNION OPERATOR
SELECT * FROM A UNION SELECT * FROM B;
SELECT * FROM A UNION ALL SELECT * FROM B;




