-- BUILT IN FUNCTIONS IN SQL

-- STRING FUNCTION
SELECT UPPER('anik');
SELECT LOWER('ANIK');
SELECT LENGTH('WELCOME');
SELECT TRIM('  WELCOME  ');
SELECT TRIM('Z' FROM 'ZZSAMSUNGZZ');
SELECT INSTR('ANIK', 'I');
SELECT SUBSTR('WELCOME', 1,3);
SELECT CONCAT('WELCOME', 'HOME');

-- SPECIFYING THE DATABASE
USE MYDB;

-- RETRIVING DATA FROM THE TABLE
SELECT * FROM NSTUDENT;

-- APPLYING STRING FUNCTION ON THE TABLE
SELECT UPPER(STUNAME) FROM NSTUDENT;
SELECT LOWER(STUNAME) FROM NSTUDENT;

-- PRINTING THE STUDENT NAME WHOSE NAME IS 4 CHARACTER LONG
SELECT * FROM NSTUDENT WHERE LENGTH(STUNAME)=4;

