-- CREATING A DATABASE 
CREATE DATABASE mydb;

-- DELETING A DATABASE
DROP DATABASE mydb;

-- CREATING A TABLE
USE mydb;
CREATE TABLE STUDENT(
	ID INT(5),
    FNAME VARCHAR(10),
    MARKS VARCHAR(5));
    
-- DESCRIBING THE TABLE
DESCRIBE STUDENT;

-- INSERTING DATA INTO THE TABLE
INSERT INTO STUDENT VALUES(101, 'ANIK', 95);
INSERT INTO STUDENT VALUES(102, 'ASHIM', 85);
INSERT INTO STUDENT VALUES(103, 'SHILA', 89);
INSERT INTO STUDENT VALUES(104, 'DHIMAN', 65);
INSERT INTO STUDENT VALUES(105, 'RAHUL', 69);

-- OTHER WAYS OF INSERTING DATA INTO TABLE
INSERT INTO STUDENT(FNAME, MARKS, ID) VALUES('RAYHAN', 76, 106);
INSERT INTO STUDENT VALUES(107, 'AFRIN', NULL);
INSERT INTO STUDENT VALUES(108, 'SANGITA', NULL);

-- SELECT OR RETRIVE THE DATA FROM A TABLE
SELECT * FROM STUDENT;

-- OTHER WAYS OF SELECTING ROWS FROM A TABLE
SELECT FNAME FROM STUDENT;
SELECT FNAME, MARKS FROM STUDENT;

-- SELECTING ROWS WITH ALIAS
SELECT ID STUDENT_ID, FNAME FIRST_NAME, MARKS+5 MARKS FROM STUDENT;

-- FILTERING RECORDS BASED ON CONDITION (WHERE CLAUSE)
SELECT * FROM STUDENT WHERE MARKS > 80;
SELECT * FROM STUDENT WHERE MARKS <= 85;
SELECT * FROM STUDENT WHERE ID=107;
SELECT * FROM STUDENT WHERE FNAME='ANIK';

-- USE OF AND, OR, NULL, NOT OPERATOR
SELECT * FROM STUDENT WHERE MARKS IS NULL;
SELECT * FROM STUDENT WHERE FNAME='ANIK' OR FNAME='AFRIN';
SELECT * FROM STUDENT WHERE ID=101 AND FNAME='ANIK';
SELECT * FROM STUDENT WHERE NOT FNAME='SHILA';
SELECT DISTINCT * FROM STUDENT WHERE ID=101 OR ID=102 OR ID=103;

-- USE OF BETWEEN & IN OPERATOR
SELECT * FROM STUDENT WHERE MARKS BETWEEN 60 AND 80;
SELECT FNAME, MARKS FROM STUDENT WHERE MARKS NOT BETWEEN 60 AND 80;
SELECT FNAME, MARKS, ID FROM STUDENT WHERE ID IN(101, 103, 105);

-- DISPLAY UNIQUE RECORDS FROM TABLE
SELECT DISTINCT * FROM STUDENT;
SELECT DISTINCT FNAME FROM STUDENT;

-- WILDCARD CHARCTER OR PATTERN MATCHING OPERATOR
SELECT * FROM STUDENT WHERE FNAME LIKE 'S%';
SELECT * FROM STUDENT WHERE FNAME LIKE '%A';
SELECT DISTINCT * FROM STUDENT WHERE FNAME LIKE '%I%';
SELECT DISTINCT * FROM STUDENT WHERE FNAME LIKE '_____';
