-- SQL SUB QUERRY

-- LETS LOOK AT THE SCENARIO FIRST
-- DISPLAY EMPLOYEES WHOSE SALARY IS LESS THEN THE 'Rayhan' SALARY 

USE MYDB;
SELECT * FROM EMPLOYEE;
SELECT SALARY FROM EMPLOYEE WHERE FIRST_NAME='Rayhan'; -- Rayhan salary = '60000'
SELECT SALARY FROM EMPLOYEE WHERE SALARY < 60000;

-- INSTEAD OF WRITING TWO QUERRY USE WRITE SUB QUERRY
SELECT SALARY FROM EMPLOYEE WHERE SALARY < (SELECT SALARY FROM EMPLOYEE WHERE FIRST_NAME='Rayhan');
