CREATE DATABASE SQLJOIN;

USE SQLJOIN;

CREATE TABLE EMPLOYEES(
	EMPLOYEE_ID INT(10),
    FIRST_NAME VARCHAR(15),
    LAST_NAME VARCHAR(15),
    EMAIL VARCHAR(20),
    PHONE_NUMBER INT(20),
    MANAGER_ID VARCHAR(20),
    DEPARTMENT_ID INT(15));
    
DESCRIBE EMPLOYEES;

CREATE TABLE DEPARTMENT(
	DEPARTMENT_ID INT(10),
    DEPARTMENT_NAME VARCHAR(15),
    MANAGER_ID VARCHAR(10),
    LOCATION_ID INT(10),
    ADDRESS VARCHAR(15));

DESCRIBE DEPARTMENT;


SELECT * FROM EMPLOYEES;
SELECT * FROM DEPARTMENT;

SET SQL_SAFE_UPDATES = 0;

DELETE FROM EMPLOYEES;
DELETE FROM DEPARTMENT;


-- INSERTING INTO EMPLOYEES (BEFORE INNER & LEFT JOIN)
INSERT INTO EMPLOYEES VALUES(101,'Anik','Das','anik@gmail.com',43254,'M101',10);
INSERT INTO EMPLOYEES VALUES(102,'Ashim','Mitra','ashim@gmail.com',43250,'M102',20);
INSERT INTO EMPLOYEES VALUES(103,'Rahul','Das','rahul@gmail.com',43246,'M103',30);
INSERT INTO EMPLOYEES VALUES(104,'Rayhan','Khan','rayhan@gmail.com',43242,'M104',40);

-- INSERTING INTO DEPARTMENT (BEFORE INNER & LEFT JOIN)
INSERT INTO DEPARTMENT VALUES(10,'Admistration','M101',1500,'Gazipur');
INSERT INTO DEPARTMENT VALUES(20,'Marketing','M102',1700,'Gazipur');


-- INNER JOIN
SELECT * FROM EMPLOYEES INNER JOIN DEPARTMENT
ON EMPLOYEES.DEPARTMENT_ID=DEPARTMENT.DEPARTMENT_ID;

-- LEFT JOIN
SELECT * FROM EMPLOYEES LEFT JOIN DEPARTMENT
ON EMPLOYEES.DEPARTMENT_ID=DEPARTMENT.DEPARTMENT_ID;

-- INSERTING INTO DEPARTMENT (FOR RIGHT JOIN)
INSERT INTO DEPARTMENT VALUES(30,'Purchasing','M103',1400,'Narsingdi');
INSERT INTO DEPARTMENT VALUES(40,'Human Resource','M104',1100,'Narsingdi');
INSERT INTO DEPARTMENT VALUES(50,'Shipping','M105',1300,'Dinajpur');
INSERT INTO DEPARTMENT VALUES(60,'IT','M106',1800,'Narsingdi');

-- RIGHT JOIN
SELECT * FROM EMPLOYEES RIGHT JOIN DEPARTMENT
ON EMPLOYEES.DEPARTMENT_ID=DEPARTMENT.DEPARTMENT_ID;

-- FULL JOIN
SELECT * FROM EMPLOYEES FULL JOIN DEPARTMENT;

-- SELF JOIN
SELECT * FROM EMPLOYEES SELF JOIN EMPLOYEES;